Repository EasyMicroservices/Serialization, pull requests merged in 2022-12, with the labels that each got.

#2 add interfaces ,Serialization #1
  src/CSharp/EasyMicroservice.Serialization.Tests/EasyMicroservice.Serialization.Tests.csproj
  src/CSharp/EasyMicroservice.Serialization.sln
  src/CSharp/EasyMicroservice.Serialization/EasyMicroservice.Serialization.csproj
  src/CSharp/EasyMicroservice.Serialization/Interfaces/IBaseSerialization.cs
  src/CSharp/EasyMicroservice.Serialization/Interfaces/IBinerySerialization.cs
  src/CSharp/EasyMicroservice.Serialization/Interfaces/IJsonSerialization.cs
  src/CSharp/EasyMicroservice.Serialization/Interfaces/ISerialization.cs
  src/CSharp/EasyMicroservice.Serialization/Interfaces/IXmlSerialization.cs
Labels: enhancement

#8 refactor namespace #7
  src/CSharp/EasyMicroservices.Serialization.BinaryGo/EasyMicroservices.Serialization.BinaryGo.csproj
  src/CSharp/EasyMicroservices.Serialization.BinaryGo/Providers/BinaryGoProvider.cs
  src/CSharp/EasyMicroservices.Serialization.NewtonSoft.Json/EasyMicroservices.Serialization.Newtonsoft.Json.csproj
  src/CSharp/EasyMicroservices.Serialization.NewtonSoft.Json/Providers/NewtonsoftJsonProvider.cs
  src/CSharp/EasyMicroservices.Serialization.System.Text.Json/EasyMicroservices.Serialization.System.Text.Json.csproj
  src/CSharp/EasyMicroservices.Serialization.System.Text.Json/Providers/SystemTextJsonBinaryProvider.cs
  src/CSharp/EasyMicroservices.Serialization.System.Text.Json/Providers/SystemTextJsonProvider.cs
  src/CSharp/EasyMicroservices.Serialization.Tests/EasyMicroservices.Serialization.Tests.csproj
  src/CSharp/EasyMicroservices.Serialization.Tests/Providers/BaseTextSerilizationTest.cs
  src/CSharp/EasyMicroservices.Serialization.sln
  src/CSharp/EasyMicroservices.Serialization/EasyMicroservices.Serialization.csproj
  src/CSharp/EasyMicroservices.Serialization/Interfaces/IBaseSerialization.cs
  src/CSharp/EasyMicroservices.Serialization/Interfaces/IBinarySerialization.cs
  src/CSharp/EasyMicroservices.Serialization/Interfaces/ITextSerialization.cs
  src/CSharp/EasyMicroservices.Serialization/Providers/BaseBinarySerializationProvider.cs
  src/CSharp/EasyMicroservices.Serialization/Providers/BaseProvider.cs
  src/CSharp/EasyMicroservices.Serialization/Providers/BaseTextSerializationProvider.cs
Labels: refactor

#9 add comment #6
  src/CSharp/EasyMicroservices.Serialization.BinaryGo/Providers/BinaryGoProvider.cs
  src/CSharp/EasyMicroservices.Serialization.NewtonSoft.Json/Providers/NewtonsoftJsonProvider.cs
  src/CSharp/EasyMicroservices.Serialization.System.Text.Json/Providers/SystemTextJsonBinaryProvider.cs
  src/CSharp/EasyMicroservices.Serialization.System.Text.Json/Providers/SystemTextJsonProvider.cs
  src/CSharp/EasyMicroservices.Serialization.Tests/Providers/BaseTextSerilizationTest.cs
  src/CSharp/EasyMicroservices.Serialization/Interfaces/IBaseSerialization.cs
  src/CSharp/EasyMicroservices.Serialization/Interfaces/IBinarySerialization.cs
  src/CSharp/EasyMicroservices.Serialization/Interfaces/ITextSerialization.cs
  src/CSharp/EasyMicroservices.Serialization/Providers/BaseBinarySerializationProvider.cs
  src/CSharp/EasyMicroservices.Serialization/Providers/BaseProvider.cs
  src/CSharp/EasyMicroservices.Serialization/Providers/BaseTextSerializationProvider.cs
Labels: documentation

#12 Refactor EasyMicroservices.Serialization project's refrence in other …
  src/CSharp/EasyMicroservices.Serialization.BinaryGo/EasyMicroservices.Serialization.BinaryGo.csproj
  src/CSharp/EasyMicroservices.Serialization.NewtonSoft.Json/EasyMicroservices.Serialization.Newtonsoft.Json.csproj
  src/CSharp/EasyMicroservices.Serialization.System.Text.Json/EasyMicroservices.Serialization.System.Text.Json.csproj
  src/CSharp/EasyMicroservices.Serialization.Tests/EasyMicroservices.Serialization.Tests.csproj
Labels: good first issue, refactor

#15 Write test #4
  src/CSharp/EasyMicroservices.Serialization.NewtonSoft.Json/Providers/NewtonsoftJsonProvider.cs
  src/CSharp/EasyMicroservices.Serialization.System.Text.Json/Providers/SystemTextJsonBinaryProvider.cs
  src/CSharp/EasyMicroservices.Serialization.System.Text.Json/Providers/SystemTextJsonProvider.cs
  src/CSharp/EasyMicroservices.Serialization.Tests/EasyMicroservices.Serialization.Tests.csproj
  src/CSharp/EasyMicroservices.Serialization.Tests/Providers/BaseTextSerilizationTest.cs
  src/CSharp/EasyMicroservices.Serialization.Tests/Providers/TextSerilization/BaseTextSerilizationTest.cs
  src/CSharp/EasyMicroservices.Serialization.Tests/Providers/TextSerilization/NewtonsoftJsonTest.cs
  src/CSharp/EasyMicroservices.Serialization.Tests/Providers/TextSerilization/SystemTextJsonTest.cs
Labels: test

#17 automate dotnet format + .editorconfig + init format
  .editorconfig
  .github/workflows/dotnet-format-action.yml
  src/CSharp/EasyMicroservices.Serialization.BinaryGo/Providers/BinaryGoProvider.cs
  src/CSharp/EasyMicroservices.Serialization.NewtonSoft.Json/Providers/NewtonsoftJsonProvider.cs
  src/CSharp/EasyMicroservices.Serialization.System.Text.Json/Providers/SystemTextJsonBinaryProvider.cs
  src/CSharp/EasyMicroservices.Serialization.System.Text.Json/Providers/SystemTextJsonProvider.cs
  src/CSharp/EasyMicroservices.Serialization.Tests/Providers/TextSerilization/BaseTextSerilizationTest.cs
  src/CSharp/EasyMicroservices.Serialization/Providers/BaseBinarySerializationProvider.cs
  src/CSharp/EasyMicroservices.Serialization/Providers/BaseProvider.cs
  src/CSharp/EasyMicroservices.Serialization/Providers/BaseTextSerializationProvider.cs
Labels: refactor

#25 add test
  src/CSharp/EasyMicroservices.Serialization.Tests/EasyMicroservices.Serialization.Tests.csproj
  src/CSharp/EasyMicroservices.Serialization.Tests/Providers/BinarySerialization/BaseBinarySerializationTest.cs
  src/CSharp/EasyMicroservices.Serialization.Tests/Providers/BinarySerialization/BinaryGoSerializationTest.cs
  src/CSharp/EasyMicroservices.Serialization.Tests/Providers/TextSerialization/BaseTextSerializationTest.cs
  src/CSharp/EasyMicroservices.Serialization.Tests/Providers/TextSerialization/NewtonsoftJsonSerializationTest.cs
  src/CSharp/EasyMicroservices.Serialization.Tests/Providers/TextSerialization/SystemTextJsonSerializationTest.cs
  src/CSharp/EasyMicroservices.Serialization.Tests/Providers/TextSerialization/YamlDotNetSerializationTest.cs
  src/CSharp/EasyMicroservices.Serialization.YamlDotNet/Providers/DotNetYamlProvider.cs
Labels: test

#29 pass yml test in linux #28
  src/CSharp/EasyMicroservices.Serialization.Tests/Providers/BinarySerialization/BaseBinarySerializationTest.cs
  src/CSharp/EasyMicroservices.Serialization.Tests/Providers/TextSerialization/BaseTextSerializationTest.cs
  src/CSharp/EasyMicroservices.Serialization.Tests/Providers/TextSerialization/YamlDotNetSerializationTest.cs
Labels: bug

#19 feat : add memory pack
  src/CSharp/EasyMicroservices.Serialization.MemoryPack/EasyMicroservices.Serialization.MemoryPack.csproj
  src/CSharp/EasyMicroservices.Serialization.MemoryPack/Providers/MemoryPackProvider.cs
  src/CSharp/EasyMicroservices.Serialization.sln
Labels: enhancement

#31 Add Xml Serializer
  src/CSharp/EasyMicroservices.Serialization.System.Text.Xml/EasyMicroservices.Serialization.System.Text.Xml.csproj
  src/CSharp/EasyMicroservices.Serialization.System.Text.Xml/Providers/SystemTextXmlProvider.cs
  src/CSharp/EasyMicroservices.Serialization.Tests/EasyMicroservices.Serialization.Tests.csproj
  src/CSharp/EasyMicroservices.Serialization.Tests/Providers/TextSerialization/SystemTextXmlSerializationTest.cs
  src/CSharp/EasyMicroservices.Serialization.sln
Labels: enhancement

#34 Remove duplication of YamlDotNet in sln
  src/CSharp/EasyMicroservices.Serialization.MemoryPack/Providers/MemoryPackProvider.cs
  src/CSharp/EasyMicroservices.Serialization.sln
Labels: bug

#18 feat: add MessagePackProvider
  src/CSharp/EasyMicroservices.Serialization.MessagePack/EasyMicroservices.Serialization.MessagePack.csproj
  src/CSharp/EasyMicroservices.Serialization.MessagePack/Providers/MessagePackProvider.cs
  src/CSharp/EasyMicroservices.Serialization.Tests/EasyMicroservices.Serialization.Tests.csproj
  src/CSharp/EasyMicroservices.Serialization.Tests/Providers/BinarySerialization/BaseBinarySerializationTest.cs
  src/CSharp/EasyMicroservices.Serialization.Tests/Providers/BinarySerialization/BinaryGoSerializationTest.cs
  src/CSharp/EasyMicroservices.Serialization.Tests/Providers/BinarySerialization/MessagePackSerializationTests.cs
  src/CSharp/EasyMicroservices.Serialization.Tests/Providers/Models/ClassToSerialize.cs
  src/CSharp/EasyMicroservices.Serialization.Tests/Providers/TextSerialization/BaseTextSerializationTest.cs
  src/CSharp/EasyMicroservices.Serialization.sln
Labels: enhancement

#36 Refactor with and add more dotnet versions with some fixes
  src/CSharp/EasyMicroservices.Serialization.BinaryGo/EasyMicroservices.Serialization.BinaryGo.csproj
  src/CSharp/EasyMicroservices.Serialization.BinaryGo/Providers/BinaryGoProvider.cs
  src/CSharp/EasyMicroservices.Serialization.MemoryPack/EasyMicroservices.Serialization.MemoryPack.csproj
  src/CSharp/EasyMicroservices.Serialization.MemoryPack/Providers/MemoryPackProvider.cs
  src/CSharp/EasyMicroservices.Serialization.MessagePack/EasyMicroservices.Serialization.MessagePack.csproj
  src/CSharp/EasyMicroservices.Serialization.MessagePack/Providers/MessagePackProvider.cs
  src/CSharp/EasyMicroservices.Serialization.NewtonSoft.Json/EasyMicroservices.Serialization.Newtonsoft.Json.csproj
  src/CSharp/EasyMicroservices.Serialization.NewtonSoft.Json/Providers/NewtonsoftJsonProvider.cs
  src/CSharp/EasyMicroservices.Serialization.System.Text.Json/EasyMicroservices.Serialization.System.Text.Json.csproj
  src/CSharp/EasyMicroservices.Serialization.System.Text.Json/Providers/SystemTextJsonBinaryProvider.cs
  src/CSharp/EasyMicroservices.Serialization.System.Text.Json/Providers/SystemTextJsonProvider.cs
  src/CSharp/EasyMicroservices.Serialization.System.Text.Xml/EasyMicroservices.Serialization.System.Text.Xml.csproj
  src/CSharp/EasyMicroservices.Serialization.System.Text.Xml/Providers/SystemTextXmlProvider.cs
  src/CSharp/EasyMicroservices.Serialization.Tests/EasyMicroservices.Serialization.Tests.csproj
  src/CSharp/EasyMicroservices.Serialization.Tests/Providers/BinarySerialization/MessagePackSerializationTests.cs
  src/CSharp/EasyMicroservices.Serialization.Tests/Providers/Models/ClassToSerialize.cs
  src/CSharp/EasyMicroservices.Serialization.Tests/Providers/TextSerialization/BaseTextSerializationTest.cs
  src/CSharp/EasyMicroservices.Serialization.Tests/Providers/TextSerialization/NewtonsoftJsonSerializationTest.cs
  src/CSharp/EasyMicroservices.Serialization.Tests/Providers/TextSerialization/SystemTextJsonSerializationTest.cs
  src/CSharp/EasyMicroservices.Serialization.Tests/Providers/TextSerialization/SystemTextXmlSerializationTest.cs
  src/CSharp/EasyMicroservices.Serialization.Tests/Providers/TextSerialization/YamlDotNetSerializationTest.cs
  src/CSharp/EasyMicroservices.Serialization.YamlDotNet/EasyMicroservices.Serialization.YamlDotNet.csproj
  src/CSharp/EasyMicroservices.Serialization.YamlDotNet/Providers/DotNetYamlProvider.cs
  src/CSharp/EasyMicroservices.Serialization.sln
  src/CSharp/EasyMicroservices.Serialization/EasyMicroservices.Serialization.csproj
  src/CSharp/EasyMicroservices.Serialization/Providers/BinarySerializationBaseProvider.cs
  src/CSharp/EasyMicroservices.Serialization/Providers/TextSerializationBaseProvider.cs
Labels: enhancement, refactor

#37 ci: use windows env and path style on NuGet Push Public
  .github/workflows/nuget-push-public.yml
Labels: enhancement
