Repository EasyMicroservices/Serialization, pull requests merged in 2023-01, with the labels that each got.

#38 Remove Abstraction from packages
  src/CSharp/EasyMicroservices.Serialization/EasyMicroservices.Serialization.csproj
Labels: bug, enhancement

#40 Add github templates.
  .github/ISSUE_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: documentation

#41 ci: add test coverage badge to README.md
  .github/workflows/dotnet-format-action.yml
  README.md
  src/CSharp/EasyMicroservices.Serialization.Tests/EasyMicroservices.Serialization.Tests.csproj
  src/CSharp/coverage-badge-branch.svg
  src/CSharp/coverage-badge-line.svg
Labels: enhancement, DevOps

#43 add sample for how to use message package
  Samples/CSharp/ASPCore/WebAPISampleProject/WebAPISampleProject.sln
  Samples/CSharp/ASPCore/WebAPISampleProject/WebAPISampleProject/Controllers/BinaryGoController.cs
  Samples/CSharp/ASPCore/WebAPISampleProject/WebAPISampleProject/Controllers/MessagePackController.cs
  Samples/CSharp/ASPCore/WebAPISampleProject/WebAPISampleProject/Models/User.cs
  Samples/CSharp/ASPCore/WebAPISampleProject/WebAPISampleProject/Program.cs
  Samples/CSharp/ASPCore/WebAPISampleProject/WebAPISampleProject/Properties/launchSettings.json
  Samples/CSharp/ASPCore/WebAPISampleProject/WebAPISampleProject/WeatherForecast.cs
  Samples/CSharp/ASPCore/WebAPISampleProject/WebAPISampleProject/WebAPISampleProject.csproj
  Samples/CSharp/ASPCore/WebAPISampleProject/WebAPISampleProject/appsettings.Development.json
  Samples/CSharp/ASPCore/WebAPISampleProject/WebAPISampleProject/appsettings.json
  Samples/CSharp/ASPCore/WebAPISampleProject/global.json
Labels: Documentation and Samples

#45 The Projects were seperated.
  Samples/CSharp/ASPCore/WebAPISampleProject/Common/Common.csproj
  Samples/CSharp/ASPCore/WebAPISampleProject/Common/Models/Customer.cs
  Samples/CSharp/ASPCore/WebAPISampleProject/Common/Models/Order.cs
  Samples/CSharp/ASPCore/WebAPISampleProject/WebAPISampleProject.BinaryGo/Controllers/BinaryGoController.cs
  Samples/CSharp/ASPCore/WebAPISampleProject/WebAPISampleProject.BinaryGo/Program.cs
  Samples/CSharp/ASPCore/WebAPISampleProject/WebAPISampleProject.BinaryGo/Properties/launchSettings.json
  Samples/CSharp/ASPCore/WebAPISampleProject/WebAPISampleProject.BinaryGo/WebAPISampleProject.BinaryGo.csproj
  Samples/CSharp/ASPCore/WebAPISampleProject/WebAPISampleProject.BinaryGo/appsettings.Development.json
  Samples/CSharp/ASPCore/WebAPISampleProject/WebAPISampleProject.BinaryGo/appsettings.json
  Samples/CSharp/ASPCore/WebAPISampleProject/WebAPISampleProject.MemoryPack/Program.cs
  Samples/CSharp/ASPCore/WebAPISampleProject/WebAPISampleProject.MemoryPack/Properties/launchSettings.json
  Samples/CSharp/ASPCore/WebAPISampleProject/WebAPISampleProject.MemoryPack/WeatherForecast.cs
  Samples/CSharp/ASPCore/WebAPISampleProject/WebAPISampleProject.MemoryPack/WebAPISampleProject.MemoryPack.csproj
  Samples/CSharp/ASPCore/WebAPISampleProject/WebAPISampleProject.MemoryPack/appsettings.Development.json
  Samples/CSharp/ASPCore/WebAPISampleProject/WebAPISampleProject.MemoryPack/appsettings.json
  Samples/CSharp/ASPCore/WebAPISampleProject/WebAPISampleProject.MessagePack/Controllers/MessagePackController.cs
  Samples/CSharp/ASPCore/WebAPISampleProject/WebAPISampleProject.MessagePack/Program.cs
  Samples/CSharp/ASPCore/WebAPISampleProject/WebAPISampleProject.MessagePack/Properties/launchSettings.json
  Samples/CSharp/ASPCore/WebAPISampleProject/WebAPISampleProject.MessagePack/WebAPISampleProject.MessagePack.csproj
  Samples/CSharp/ASPCore/WebAPISampleProject/WebAPISampleProject.MessagePack/appsettings.Development.json
  Samples/CSharp/ASPCore/WebAPISampleProject/WebAPISampleProject.MessagePack/appsettings.json
  Samples/CSharp/ASPCore/WebAPISampleProject/WebAPISampleProject.NewtonSoft.Json/Controllers/WeatherForecastController.cs
  Samples/CSharp/ASPCore/WebAPISampleProject/WebAPISampleProject.NewtonSoft.Json/Program.cs
  Samples/CSharp/ASPCore/WebAPISampleProject/WebAPISampleProject.NewtonSoft.Json/Properties/launchSettings.json
  Samples/CSharp/ASPCore/WebAPISampleProject/WebAPISampleProject.NewtonSoft.Json/WeatherForecast.cs
  Samples/CSharp/ASPCore/WebAPISampleProject/WebAPISampleProject.NewtonSoft.Json/WebAPISampleProject.NewtonSoft.Json.csproj
  Samples/CSharp/ASPCore/WebAPISampleProject/WebAPISampleProject.NewtonSoft.Json/appsettings.Development.json
  Samples/CSharp/ASPCore/WebAPISampleProject/WebAPISampleProject.NewtonSoft.Json/appsettings.json
  Samples/CSharp/ASPCore/WebAPISampleProject/WebAPISampleProject.System.Text.Json/Controllers/WeatherForecastController.cs
  Samples/CSharp/ASPCore/WebAPISampleProject/WebAPISampleProject.System.Text.Json/Program.cs
  Samples/CSharp/ASPCore/WebAPISampleProject/WebAPISampleProject.System.Text.Json/Properties/launchSettings.json
  Samples/CSharp/ASPCore/WebAPISampleProject/WebAPISampleProject.System.Text.Json/WeatherForecast.cs
  Samples/CSharp/ASPCore/WebAPISampleProject/WebAPISampleProject.System.Text.Json/WebAPISampleProject.System.Text.Json.csproj
  Samples/CSharp/ASPCore/WebAPISampleProject/WebAPISampleProject.System.Text.Json/appsettings.Development.json
  Samples/CSharp/ASPCore/WebAPISampleProject/WebAPISampleProject.System.Text.Json/appsettings.json
  Samples/CSharp/ASPCore/WebAPISampleProject/WebAPISampleProject.System.Text.Xml/Controllers/WeatherForecastController.cs
  Samples/CSharp/ASPCore/WebAPISampleProject/WebAPISampleProject.System.Text.Xml/Program.cs
  Samples/CSharp/ASPCore/WebAPISampleProject/WebAPISampleProject.System.Text.Xml/Properties/launchSettings.json
  Samples/CSharp/ASPCore/WebAPISampleProject/WebAPISampleProject.System.Text.Xml/WeatherForecast.cs
  Samples/CSharp/ASPCore/WebAPISampleProject/WebAPISampleProject.System.Text.Xml/WebAPISampleProject.System.Text.Xml.csproj
  Samples/CSharp/ASPCore/WebAPISampleProject/WebAPISampleProject.System.Text.Xml/appsettings.Development.json
  Samples/CSharp/ASPCore/WebAPISampleProject/WebAPISampleProject.System.Text.Xml/appsettings.json
  Samples/CSharp/ASPCore/WebAPISampleProject/WebAPISampleProject.System.YamlDotNet/Controllers/YamlDotNetController.cs
  Samples/CSharp/ASPCore/WebAPISampleProject/WebAPISampleProject.System.YamlDotNet/Program.cs
  Samples/CSharp/ASPCore/WebAPISampleProject/WebAPISampleProject.System.YamlDotNet/Properties/launchSettings.json
  Samples/CSharp/ASPCore/WebAPISampleProject/WebAPISampleProject.System.YamlDotNet/WebAPISampleProject.System.YamlDotNet.csproj
  Samples/CSharp/ASPCore/WebAPISampleProject/WebAPISampleProject.System.YamlDotNet/appsettings.Development.json
  Samples/CSharp/ASPCore/WebAPISampleProject/WebAPISampleProject.System.YamlDotNet/appsettings.json
  Samples/CSharp/ASPCore/WebAPISampleProject/WebAPISampleProject.sln
  Samples/CSharp/ASPCore/WebAPISampleProject/WebAPISampleProject/Controllers/MessagePackController.cs
Labels: Documentation and Samples

#46 Use Generic parameter instead of object.
  src/CSharp/EasyMicroservices.Serialization.NewtonSoft.Json/Providers/NewtonsoftJsonProvider.cs
  src/CSharp/EasyMicroservices.Serialization.System.Text.Json/Providers/SystemTextJsonProvider.cs
  src/CSharp/EasyMicroservices.Serialization.System.Text.Xml/Providers/SystemTextXmlProvider.cs
  src/CSharp/EasyMicroservices.Serialization.YamlDotNet/Providers/DotNetYamlProvider.cs
  src/CSharp/EasyMicroservices.Serialization/Interfaces/IBaseSerialization.cs
  src/CSharp/EasyMicroservices.Serialization/Interfaces/ITextSerialization.cs
  src/CSharp/EasyMicroservices.Serialization/Providers/TextSerializationBaseProvider.cs
Labels: Breaking Change

#47 Added Text Serialization Samples
  Samples/CSharp/ASPCore/WebAPISampleProject/Common/Models/Customer.cs
  Samples/CSharp/ASPCore/WebAPISampleProject/WebAPISampleProject.MemoryPack/Controllers/MemoryPackController.cs
  Samples/CSharp/ASPCore/WebAPISampleProject/WebAPISampleProject.MemoryPack/Program.cs
  Samples/CSharp/ASPCore/WebAPISampleProject/WebAPISampleProject.MemoryPack/WeatherForecast.cs
  Samples/CSharp/ASPCore/WebAPISampleProject/WebAPISampleProject.MemoryPack/WebAPISampleProject.MemoryPack.csproj
  Samples/CSharp/ASPCore/WebAPISampleProject/WebAPISampleProject.NewtonSoft.Json/Controllers/NewtonSoftJsonController.cs
  Samples/CSharp/ASPCore/WebAPISampleProject/WebAPISampleProject.NewtonSoft.Json/Controllers/WeatherForecastController.cs
  Samples/CSharp/ASPCore/WebAPISampleProject/WebAPISampleProject.NewtonSoft.Json/Program.cs
  Samples/CSharp/ASPCore/WebAPISampleProject/WebAPISampleProject.NewtonSoft.Json/WeatherForecast.cs
  Samples/CSharp/ASPCore/WebAPISampleProject/WebAPISampleProject.NewtonSoft.Json/WebAPISampleProject.NewtonSoft.Json.csproj
  Samples/CSharp/ASPCore/WebAPISampleProject/WebAPISampleProject.System.Text.Json/Controllers/SystemTextJsonBinaryController.cs
  Samples/CSharp/ASPCore/WebAPISampleProject/WebAPISampleProject.System.Text.Json/Controllers/SystemTextJsonController.cs
  Samples/CSharp/ASPCore/WebAPISampleProject/WebAPISampleProject.System.Text.Json/Controllers/WeatherForecastController.cs
  Samples/CSharp/ASPCore/WebAPISampleProject/WebAPISampleProject.System.Text.Json/Program.cs
  Samples/CSharp/ASPCore/WebAPISampleProject/WebAPISampleProject.System.Text.Json/WeatherForecast.cs
  Samples/CSharp/ASPCore/WebAPISampleProject/WebAPISampleProject.System.Text.Json/WebAPISampleProject.System.Text.Json.csproj
  Samples/CSharp/ASPCore/WebAPISampleProject/WebAPISampleProject.System.Text.Xml/Controllers/SystemTextXmlController.cs
  Samples/CSharp/ASPCore/WebAPISampleProject/WebAPISampleProject.System.Text.Xml/Controllers/WeatherForecastController.cs
  Samples/CSharp/ASPCore/WebAPISampleProject/WebAPISampleProject.System.Text.Xml/Program.cs
  Samples/CSharp/ASPCore/WebAPISampleProject/WebAPISampleProject.System.Text.Xml/WeatherForecast.cs
  Samples/CSharp/ASPCore/WebAPISampleProject/WebAPISampleProject.System.Text.Xml/WebAPISampleProject.System.Text.Xml.csproj
Labels: Documentation and Samples
